# Generated by Django 5.1.4 on 2025-01-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('skus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='products.product'),
        ),
    ]
