# Generated by Django 5.1.4 on 2025-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True),
        ),
    ]
